### ISSUE TITLE
Left and right channels reversed

### ISSUE THREAD

**Issue by mrlinuxfish** [ploopyco/headphones#12]
The audio output for the left channel is being sent to the right ear cup and vice verses.

Looking at the driver boards, the tip is only connected on the right side and the ring is only connected on the left side. According to convention, the tip is for left / mono audio and the ring is for the right channel.

A workaround can be wearing the headphones backwards, but it is much more elegant to have the cable come out of the correct side of the headphones (this will also reduce strain on the cables)

**Comment by ploopyco** [comment]
I'm guessing we've talked about this on Discord/Reddit since, so I'll just close this issue with some notes for future readers:

As of this writing, the headphone drivers are wired *backwards* -- the left driver is connected to the canonically right channel of the TRS jack and vice versa. This is due to the fact that the supplier for our TRS splitter cable secretly reversed the connections, and we didn't think to check beyond verifying that the correct sound came from the correct side. 

If you're using a custom cable, you can use the [headphones toolbox](https://github.com/ploopyco/headphones-toolbox/releases) to flip the channels of the output signal.
